# Prometheus configuration for SledzSpecke
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'sledzspecke-monitor'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files:
  - "alert_rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # SledzSpecke API metrics
  - job_name: 'sledzspecke-api'
    static_configs:
      - targets: ['api:5000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # PostgreSQL exporter (if configured)
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Nginx exporter (if configured)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']