#!/bin/bash
# Manual DevOps setup instructions

echo "📋 Manual DevOps Setup Instructions for SledzSpecke"
echo "=================================================="
echo ""
echo "If the automatic deployment is taking too long or fails, follow these steps:"
echo ""
echo "1. SSH to VPS:"
echo "   ssh ubuntu@51.77.59.184"
echo ""
echo "2. Fix Git permissions (if needed):"
echo "   cd /home/ubuntu/sledzspecke"
echo "   sudo chown -R ubuntu:ubuntu ."
echo "   git reset --hard HEAD"
echo "   git pull origin master"
echo ""
echo "3. Run DevOps improvements:"
echo "   cd /home/ubuntu/sledzspecke"
echo "   sudo bash scripts/fix-devops.sh"
echo ""
echo "4. Verify everything is working:"
echo "   bash scripts/verify-devops.sh"
echo ""
echo "5. Check services:"
echo "   sudo systemctl status sledzspecke-api"
echo "   docker ps"
echo "   curl http://localhost:5341  # Seq"
echo ""
echo "6. View logs:"
echo "   tail -f /var/log/sledzspecke/api-$(date +%Y-%m-%d).log"
echo ""
echo "=================================================="
echo ""
echo "Quick commands to copy/paste:"
echo ""
echo "# Full setup in one command:"
echo 'ssh ubuntu@51.77.59.184 "cd /home/ubuntu/sledzspecke && sudo chown -R ubuntu:ubuntu . && git pull origin master && sudo bash scripts/fix-devops.sh"'
echo ""
echo "# Just run DevOps fixes:"
echo 'ssh ubuntu@51.77.59.184 "cd /home/ubuntu/sledzspecke && sudo bash scripts/fix-devops.sh"'
echo ""
echo "# Check status:"
echo 'ssh ubuntu@51.77.59.184 "cd /home/ubuntu/sledzspecke && bash scripts/verify-devops.sh"'