---
# Ansible Galaxy requirements

collections:
  - name: community.general
    version: ">=7.0.0"
  - name: community.postgresql
    version: ">=3.0.0"
  - name: community.docker
    version: ">=3.0.0"

roles: []