name: Build MAUI App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-android:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          
      - name: Install .NET MAUI Workloads
        run: dotnet workload install maui --ignore-failed-sources
        
      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget-
        
      - name: Restore dependencies
        run: dotnet restore SledzSpecke.sln
        
      - name: Build Core and Infrastructure projects
        run: |
          dotnet build SledzSpecke.Core/SledzSpecke.Core.csproj --no-restore
          dotnet build SledzSpecke.Infrastructure/SledzSpecke.Infrastructure.csproj --no-restore
        
      - name: Build Android App
        run: dotnet build SledzSpecke.App/SledzSpecke.App.csproj -f net9.0-android35.0 --no-restore
      
      - name: Test
        run: dotnet test SledzSpecke.sln --no-build --verbosity normal || true

  build-ios:
    runs-on: macos-latest
    needs: build-android  # Run after Android build succeeds
    continue-on-error: true  # Allow workflow to continue even if iOS build fails
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Create iOS project modifications
        run: |
          echo '
          <Project>
            <PropertyGroup>
              <MtouchLink>SdkOnly</MtouchLink>
              <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier(&apos;$(TargetFramework)&apos;)) == &apos;ios&apos;">15.0</SupportedOSPlatformVersion>
              <SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier(&apos;$(TargetFramework)&apos;)) == &apos;maccatalyst&apos;">15.0</SupportedOSPlatformVersion>
            </PropertyGroup>
          </Project>
          ' > Directory.Build.props
      
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'
          
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          
      - name: Install .NET MAUI Workloads
        run: dotnet workload install maui --ignore-failed-sources
        
      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget-
        
      - name: Restore dependencies
        run: dotnet restore SledzSpecke.sln
        
      - name: Build Core and Infrastructure projects
        run: |
          dotnet build SledzSpecke.Core/SledzSpecke.Core.csproj --no-restore
          dotnet build SledzSpecke.Infrastructure/SledzSpecke.Infrastructure.csproj --no-restore
        
      - name: Build iOS App (attempt)
        run: dotnet build SledzSpecke.App/SledzSpecke.App.csproj -f net9.0-ios --no-restore || true