on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
          
      - name: Install iOS Simulator Runtime
        run: |
          sudo xcode-select --switch /Applications/Xcode.app
          sudo xcodebuild -downloadAllPlatforms

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          
      - name: Install .NET MAUI Workloads
        run: dotnet workload install maui --ignore-failed-sources

      - name: Clean and Restore
        run: |
          dotnet clean SledzSpecke.sln
          dotnet restore SledzSpecke.sln
        
      - name: Build
        run: dotnet build SledzSpecke.sln --no-restore --configuration Release
        
      - name: Test
        run: dotnet test SledzSpecke.sln --no-build --verbosity normal
